// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: mizar.proto

package mizar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_mizar_proto protoreflect.FileDescriptor

const file_mizar_proto_rawDesc = "" +
	"\n" +
	"\vmizar.proto\x12\x05mizar\x1a\x10mizar_info.proto\x1a\x11mizar_quote.proto\x1a\x15mizar_portfolio.proto\x1a\x11mizar_trade.proto\x1a\x12mizar_stream.protoB*Z(github.com/mizar/mizar-proto/proto/mizarb\x06proto3"

var file_mizar_proto_goTypes = []any{}
var file_mizar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mizar_proto_init() }
func file_mizar_proto_init() {
	if File_mizar_proto != nil {
		return
	}
	file_mizar_info_proto_init()
	file_mizar_quote_proto_init()
	file_mizar_portfolio_proto_init()
	file_mizar_trade_proto_init()
	file_mizar_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mizar_proto_rawDesc), len(file_mizar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mizar_proto_goTypes,
		DependencyIndexes: file_mizar_proto_depIdxs,
	}.Build()
	File_mizar_proto = out.File
	file_mizar_proto_goTypes = nil
	file_mizar_proto_depIdxs = nil
}
