// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: mizar_portfolio.proto

package mizar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 保證金資訊
type MarginInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	YesterdayBalance          float64                `protobuf:"fixed64,1,opt,name=yesterday_balance,json=yesterdayBalance,proto3" json:"yesterday_balance,omitempty"`                                 // 前日餘額
	TodayBalance              float64                `protobuf:"fixed64,2,opt,name=today_balance,json=todayBalance,proto3" json:"today_balance,omitempty"`                                             // 今日餘額
	DepositWithdrawal         float64                `protobuf:"fixed64,3,opt,name=deposit_withdrawal,json=depositWithdrawal,proto3" json:"deposit_withdrawal,omitempty"`                              // 存提
	Fee                       float64                `protobuf:"fixed64,4,opt,name=fee,proto3" json:"fee,omitempty"`                                                                                   // 手續費
	Tax                       float64                `protobuf:"fixed64,5,opt,name=tax,proto3" json:"tax,omitempty"`                                                                                   // 期交稅
	InitialMargin             float64                `protobuf:"fixed64,6,opt,name=initial_margin,json=initialMargin,proto3" json:"initial_margin,omitempty"`                                          // 原始保證金
	MaintenanceMargin         float64                `protobuf:"fixed64,7,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`                              // 維持保證金
	MarginCall                float64                `protobuf:"fixed64,8,opt,name=margin_call,json=marginCall,proto3" json:"margin_call,omitempty"`                                                   // 追繳保證金
	RiskIndicator             float64                `protobuf:"fixed64,9,opt,name=risk_indicator,json=riskIndicator,proto3" json:"risk_indicator,omitempty"`                                          // 風險指標
	RoyaltyRevenueExpenditure float64                `protobuf:"fixed64,10,opt,name=royalty_revenue_expenditure,json=royaltyRevenueExpenditure,proto3" json:"royalty_revenue_expenditure,omitempty"`   // 權利金收入與支出
	Equity                    float64                `protobuf:"fixed64,11,opt,name=equity,proto3" json:"equity,omitempty"`                                                                            // 權益數
	EquityAmount              float64                `protobuf:"fixed64,12,opt,name=equity_amount,json=equityAmount,proto3" json:"equity_amount,omitempty"`                                            // 權益總值
	OptionOpenbuyMarketValue  float64                `protobuf:"fixed64,13,opt,name=option_openbuy_market_value,json=optionOpenbuyMarketValue,proto3" json:"option_openbuy_market_value,omitempty"`    // 未沖銷買方選擇權市值
	OptionOpensellMarketValue float64                `protobuf:"fixed64,14,opt,name=option_opensell_market_value,json=optionOpensellMarketValue,proto3" json:"option_opensell_market_value,omitempty"` // 未沖銷賣方選擇權市值
	OptionOpenPosition        float64                `protobuf:"fixed64,15,opt,name=option_open_position,json=optionOpenPosition,proto3" json:"option_open_position,omitempty"`                        // 參考未平倉選擇權損益
	OptionSettleProfitloss    float64                `protobuf:"fixed64,16,opt,name=option_settle_profitloss,json=optionSettleProfitloss,proto3" json:"option_settle_profitloss,omitempty"`            // 參考選擇權平倉損益
	FutureOpenPosition        float64                `protobuf:"fixed64,17,opt,name=future_open_position,json=futureOpenPosition,proto3" json:"future_open_position,omitempty"`                        // 未沖銷期貨浮動損益
	TodayFutureOpenPosition   float64                `protobuf:"fixed64,18,opt,name=today_future_open_position,json=todayFutureOpenPosition,proto3" json:"today_future_open_position,omitempty"`       // 參考當日未沖銷期貨浮動損益
	FutureSettleProfitloss    float64                `protobuf:"fixed64,19,opt,name=future_settle_profitloss,json=futureSettleProfitloss,proto3" json:"future_settle_profitloss,omitempty"`            // 期貨平倉損益
	AvailableMargin           float64                `protobuf:"fixed64,20,opt,name=available_margin,json=availableMargin,proto3" json:"available_margin,omitempty"`                                   // 可動用(出金)保證金
	PlusMargin                float64                `protobuf:"fixed64,21,opt,name=plus_margin,json=plusMargin,proto3" json:"plus_margin,omitempty"`                                                  // 依「加收保證金指標」所加收之保證金
	PlusMarginIndicator       float64                `protobuf:"fixed64,22,opt,name=plus_margin_indicator,json=plusMarginIndicator,proto3" json:"plus_margin_indicator,omitempty"`                     // 加收保證金指標
	SecurityCollateralAmount  float64                `protobuf:"fixed64,23,opt,name=security_collateral_amount,json=securityCollateralAmount,proto3" json:"security_collateral_amount,omitempty"`      // 有價證券抵繳總額
	OrderMarginPremium        float64                `protobuf:"fixed64,24,opt,name=order_margin_premium,json=orderMarginPremium,proto3" json:"order_margin_premium,omitempty"`                        // 委託保證金及委託權利金
	CollateralAmount          float64                `protobuf:"fixed64,25,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount,omitempty"`                                // 有價品額
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MarginInfo) Reset() {
	*x = MarginInfo{}
	mi := &file_mizar_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarginInfo) ProtoMessage() {}

func (x *MarginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarginInfo.ProtoReflect.Descriptor instead.
func (*MarginInfo) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *MarginInfo) GetYesterdayBalance() float64 {
	if x != nil {
		return x.YesterdayBalance
	}
	return 0
}

func (x *MarginInfo) GetTodayBalance() float64 {
	if x != nil {
		return x.TodayBalance
	}
	return 0
}

func (x *MarginInfo) GetDepositWithdrawal() float64 {
	if x != nil {
		return x.DepositWithdrawal
	}
	return 0
}

func (x *MarginInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *MarginInfo) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *MarginInfo) GetInitialMargin() float64 {
	if x != nil {
		return x.InitialMargin
	}
	return 0
}

func (x *MarginInfo) GetMaintenanceMargin() float64 {
	if x != nil {
		return x.MaintenanceMargin
	}
	return 0
}

func (x *MarginInfo) GetMarginCall() float64 {
	if x != nil {
		return x.MarginCall
	}
	return 0
}

func (x *MarginInfo) GetRiskIndicator() float64 {
	if x != nil {
		return x.RiskIndicator
	}
	return 0
}

func (x *MarginInfo) GetRoyaltyRevenueExpenditure() float64 {
	if x != nil {
		return x.RoyaltyRevenueExpenditure
	}
	return 0
}

func (x *MarginInfo) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *MarginInfo) GetEquityAmount() float64 {
	if x != nil {
		return x.EquityAmount
	}
	return 0
}

func (x *MarginInfo) GetOptionOpenbuyMarketValue() float64 {
	if x != nil {
		return x.OptionOpenbuyMarketValue
	}
	return 0
}

func (x *MarginInfo) GetOptionOpensellMarketValue() float64 {
	if x != nil {
		return x.OptionOpensellMarketValue
	}
	return 0
}

func (x *MarginInfo) GetOptionOpenPosition() float64 {
	if x != nil {
		return x.OptionOpenPosition
	}
	return 0
}

func (x *MarginInfo) GetOptionSettleProfitloss() float64 {
	if x != nil {
		return x.OptionSettleProfitloss
	}
	return 0
}

func (x *MarginInfo) GetFutureOpenPosition() float64 {
	if x != nil {
		return x.FutureOpenPosition
	}
	return 0
}

func (x *MarginInfo) GetTodayFutureOpenPosition() float64 {
	if x != nil {
		return x.TodayFutureOpenPosition
	}
	return 0
}

func (x *MarginInfo) GetFutureSettleProfitloss() float64 {
	if x != nil {
		return x.FutureSettleProfitloss
	}
	return 0
}

func (x *MarginInfo) GetAvailableMargin() float64 {
	if x != nil {
		return x.AvailableMargin
	}
	return 0
}

func (x *MarginInfo) GetPlusMargin() float64 {
	if x != nil {
		return x.PlusMargin
	}
	return 0
}

func (x *MarginInfo) GetPlusMarginIndicator() float64 {
	if x != nil {
		return x.PlusMarginIndicator
	}
	return 0
}

func (x *MarginInfo) GetSecurityCollateralAmount() float64 {
	if x != nil {
		return x.SecurityCollateralAmount
	}
	return 0
}

func (x *MarginInfo) GetOrderMarginPremium() float64 {
	if x != nil {
		return x.OrderMarginPremium
	}
	return 0
}

func (x *MarginInfo) GetCollateralAmount() float64 {
	if x != nil {
		return x.CollateralAmount
	}
	return 0
}

// 期貨持倉資訊
type FuturePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 部位代碼
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 商品代碼
	Direction     Action                 `protobuf:"varint,3,opt,name=direction,proto3,enum=mizar.common.Action" json:"direction,omitempty"` // 買賣方向
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                            // 數量
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                 // 平均價格
	LastPrice     float64                `protobuf:"fixed64,6,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`        // 目前價格
	Pnl           float64                `protobuf:"fixed64,7,opt,name=pnl,proto3" json:"pnl,omitempty"`                                     // 損益
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuturePosition) Reset() {
	*x = FuturePosition{}
	mi := &file_mizar_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuturePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturePosition) ProtoMessage() {}

func (x *FuturePosition) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturePosition.ProtoReflect.Descriptor instead.
func (*FuturePosition) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *FuturePosition) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FuturePosition) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FuturePosition) GetDirection() Action {
	if x != nil {
		return x.Direction
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *FuturePosition) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *FuturePosition) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FuturePosition) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *FuturePosition) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

// 期貨持倉明細
type FuturePositionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                          // 交易日期
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                          // 商品代碼
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                 // 數量
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                                      // 價格
	LastPrice     float64                `protobuf:"fixed64,5,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`             // 目前股價
	Dseq          string                 `protobuf:"bytes,6,opt,name=dseq,proto3" json:"dseq,omitempty"`                                          // 委託書號
	Direction     Action                 `protobuf:"varint,7,opt,name=direction,proto3,enum=mizar.common.Action" json:"direction,omitempty"`      // 買賣方向
	Pnl           float64                `protobuf:"fixed64,8,opt,name=pnl,proto3" json:"pnl,omitempty"`                                          // 損益
	Currency      string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`                                  // 幣別
	Fee           float64                `protobuf:"fixed64,10,opt,name=fee,proto3" json:"fee,omitempty"`                                         // 交易手續費
	EntryQuantity int64                  `protobuf:"varint,11,opt,name=entry_quantity,json=entryQuantity,proto3" json:"entry_quantity,omitempty"` // 新倉數量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuturePositionDetail) Reset() {
	*x = FuturePositionDetail{}
	mi := &file_mizar_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuturePositionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturePositionDetail) ProtoMessage() {}

func (x *FuturePositionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturePositionDetail.ProtoReflect.Descriptor instead.
func (*FuturePositionDetail) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *FuturePositionDetail) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FuturePositionDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FuturePositionDetail) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *FuturePositionDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FuturePositionDetail) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *FuturePositionDetail) GetDseq() string {
	if x != nil {
		return x.Dseq
	}
	return ""
}

func (x *FuturePositionDetail) GetDirection() Action {
	if x != nil {
		return x.Direction
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *FuturePositionDetail) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *FuturePositionDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FuturePositionDetail) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *FuturePositionDetail) GetEntryQuantity() int64 {
	if x != nil {
		return x.EntryQuantity
	}
	return 0
}

// 取得保證金請求
type GetMarginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarginRequest) Reset() {
	*x = GetMarginRequest{}
	mi := &file_mizar_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarginRequest) ProtoMessage() {}

func (x *GetMarginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarginRequest.ProtoReflect.Descriptor instead.
func (*GetMarginRequest) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{3}
}

// 取得保證金回應
type GetMarginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarginInfo    *MarginInfo            `protobuf:"bytes,1,opt,name=margin_info,json=marginInfo,proto3" json:"margin_info,omitempty"`                           // 保證金資訊
	ErrorCode     ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarginResponse) Reset() {
	*x = GetMarginResponse{}
	mi := &file_mizar_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarginResponse) ProtoMessage() {}

func (x *GetMarginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarginResponse.ProtoReflect.Descriptor instead.
func (*GetMarginResponse) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *GetMarginResponse) GetMarginInfo() *MarginInfo {
	if x != nil {
		return x.MarginInfo
	}
	return nil
}

func (x *GetMarginResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *GetMarginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 取得期貨持倉列表請求
type GetFuturePositionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFuturePositionListRequest) Reset() {
	*x = GetFuturePositionListRequest{}
	mi := &file_mizar_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFuturePositionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuturePositionListRequest) ProtoMessage() {}

func (x *GetFuturePositionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuturePositionListRequest.ProtoReflect.Descriptor instead.
func (*GetFuturePositionListRequest) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{5}
}

// 期貨持倉列表回應
type GetFuturePositionListResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FuturePositions []*FuturePosition      `protobuf:"bytes,1,rep,name=future_positions,json=futurePositions,proto3" json:"future_positions,omitempty"`            // 期貨持倉列表
	ErrorCode       ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFuturePositionListResponse) Reset() {
	*x = GetFuturePositionListResponse{}
	mi := &file_mizar_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFuturePositionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuturePositionListResponse) ProtoMessage() {}

func (x *GetFuturePositionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuturePositionListResponse.ProtoReflect.Descriptor instead.
func (*GetFuturePositionListResponse) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *GetFuturePositionListResponse) GetFuturePositions() []*FuturePosition {
	if x != nil {
		return x.FuturePositions
	}
	return nil
}

func (x *GetFuturePositionListResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *GetFuturePositionListResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 取得期貨持倉明細請求
type GetFuturePositionDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetailId      int32                  `protobuf:"varint,1,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"` // 明細代碼（從持倉列表取得）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFuturePositionDetailRequest) Reset() {
	*x = GetFuturePositionDetailRequest{}
	mi := &file_mizar_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFuturePositionDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuturePositionDetailRequest) ProtoMessage() {}

func (x *GetFuturePositionDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuturePositionDetailRequest.ProtoReflect.Descriptor instead.
func (*GetFuturePositionDetailRequest) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{7}
}

func (x *GetFuturePositionDetailRequest) GetDetailId() int32 {
	if x != nil {
		return x.DetailId
	}
	return 0
}

// 期貨持倉明細回應
type GetFuturePositionDetailResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	FutureDetails []*FuturePositionDetail `protobuf:"bytes,1,rep,name=future_details,json=futureDetails,proto3" json:"future_details,omitempty"`                  // 期貨持倉明細
	ErrorCode     ErrorCode               `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage  string                  `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFuturePositionDetailResponse) Reset() {
	*x = GetFuturePositionDetailResponse{}
	mi := &file_mizar_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFuturePositionDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuturePositionDetailResponse) ProtoMessage() {}

func (x *GetFuturePositionDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuturePositionDetailResponse.ProtoReflect.Descriptor instead.
func (*GetFuturePositionDetailResponse) Descriptor() ([]byte, []int) {
	return file_mizar_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *GetFuturePositionDetailResponse) GetFutureDetails() []*FuturePositionDetail {
	if x != nil {
		return x.FutureDetails
	}
	return nil
}

func (x *GetFuturePositionDetailResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *GetFuturePositionDetailResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_mizar_portfolio_proto protoreflect.FileDescriptor

const file_mizar_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x15mizar_portfolio.proto\x12\x0fmizar.portfolio\x1a\x12mizar_common.proto\"\xfe\b\n" +
	"\n" +
	"MarginInfo\x12+\n" +
	"\x11yesterday_balance\x18\x01 \x01(\x01R\x10yesterdayBalance\x12#\n" +
	"\rtoday_balance\x18\x02 \x01(\x01R\ftodayBalance\x12-\n" +
	"\x12deposit_withdrawal\x18\x03 \x01(\x01R\x11depositWithdrawal\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x01R\x03fee\x12\x10\n" +
	"\x03tax\x18\x05 \x01(\x01R\x03tax\x12%\n" +
	"\x0einitial_margin\x18\x06 \x01(\x01R\rinitialMargin\x12-\n" +
	"\x12maintenance_margin\x18\a \x01(\x01R\x11maintenanceMargin\x12\x1f\n" +
	"\vmargin_call\x18\b \x01(\x01R\n" +
	"marginCall\x12%\n" +
	"\x0erisk_indicator\x18\t \x01(\x01R\rriskIndicator\x12>\n" +
	"\x1broyalty_revenue_expenditure\x18\n" +
	" \x01(\x01R\x19royaltyRevenueExpenditure\x12\x16\n" +
	"\x06equity\x18\v \x01(\x01R\x06equity\x12#\n" +
	"\requity_amount\x18\f \x01(\x01R\fequityAmount\x12=\n" +
	"\x1boption_openbuy_market_value\x18\r \x01(\x01R\x18optionOpenbuyMarketValue\x12?\n" +
	"\x1coption_opensell_market_value\x18\x0e \x01(\x01R\x19optionOpensellMarketValue\x120\n" +
	"\x14option_open_position\x18\x0f \x01(\x01R\x12optionOpenPosition\x128\n" +
	"\x18option_settle_profitloss\x18\x10 \x01(\x01R\x16optionSettleProfitloss\x120\n" +
	"\x14future_open_position\x18\x11 \x01(\x01R\x12futureOpenPosition\x12;\n" +
	"\x1atoday_future_open_position\x18\x12 \x01(\x01R\x17todayFutureOpenPosition\x128\n" +
	"\x18future_settle_profitloss\x18\x13 \x01(\x01R\x16futureSettleProfitloss\x12)\n" +
	"\x10available_margin\x18\x14 \x01(\x01R\x0favailableMargin\x12\x1f\n" +
	"\vplus_margin\x18\x15 \x01(\x01R\n" +
	"plusMargin\x122\n" +
	"\x15plus_margin_indicator\x18\x16 \x01(\x01R\x13plusMarginIndicator\x12<\n" +
	"\x1asecurity_collateral_amount\x18\x17 \x01(\x01R\x18securityCollateralAmount\x120\n" +
	"\x14order_margin_premium\x18\x18 \x01(\x01R\x12orderMarginPremium\x12+\n" +
	"\x11collateral_amount\x18\x19 \x01(\x01R\x10collateralAmount\"\xcb\x01\n" +
	"\x0eFuturePosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x122\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x14.mizar.common.ActionR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"last_price\x18\x06 \x01(\x01R\tlastPrice\x12\x10\n" +
	"\x03pnl\x18\a \x01(\x01R\x03pnl\"\xbe\x02\n" +
	"\x14FuturePositionDetail\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"last_price\x18\x05 \x01(\x01R\tlastPrice\x12\x12\n" +
	"\x04dseq\x18\x06 \x01(\tR\x04dseq\x122\n" +
	"\tdirection\x18\a \x01(\x0e2\x14.mizar.common.ActionR\tdirection\x12\x10\n" +
	"\x03pnl\x18\b \x01(\x01R\x03pnl\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\x01R\x03fee\x12%\n" +
	"\x0eentry_quantity\x18\v \x01(\x03R\rentryQuantity\"\x12\n" +
	"\x10GetMarginRequest\"\xae\x01\n" +
	"\x11GetMarginResponse\x12<\n" +
	"\vmargin_info\x18\x01 \x01(\v2\x1b.mizar.portfolio.MarginInfoR\n" +
	"marginInfo\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x1e\n" +
	"\x1cGetFuturePositionListRequest\"\xc8\x01\n" +
	"\x1dGetFuturePositionListResponse\x12J\n" +
	"\x10future_positions\x18\x01 \x03(\v2\x1f.mizar.portfolio.FuturePositionR\x0ffuturePositions\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"=\n" +
	"\x1eGetFuturePositionDetailRequest\x12\x1b\n" +
	"\tdetail_id\x18\x01 \x01(\x05R\bdetailId\"\xcc\x01\n" +
	"\x1fGetFuturePositionDetailResponse\x12L\n" +
	"\x0efuture_details\x18\x01 \x03(\v2%.mizar.portfolio.FuturePositionDetailR\rfutureDetails\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessageB*Z(github.com/mizar/mizar-proto/proto/mizarb\x06proto3"

var (
	file_mizar_portfolio_proto_rawDescOnce sync.Once
	file_mizar_portfolio_proto_rawDescData []byte
)

func file_mizar_portfolio_proto_rawDescGZIP() []byte {
	file_mizar_portfolio_proto_rawDescOnce.Do(func() {
		file_mizar_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mizar_portfolio_proto_rawDesc), len(file_mizar_portfolio_proto_rawDesc)))
	})
	return file_mizar_portfolio_proto_rawDescData
}

var file_mizar_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mizar_portfolio_proto_goTypes = []any{
	(*MarginInfo)(nil),                      // 0: mizar.portfolio.MarginInfo
	(*FuturePosition)(nil),                  // 1: mizar.portfolio.FuturePosition
	(*FuturePositionDetail)(nil),            // 2: mizar.portfolio.FuturePositionDetail
	(*GetMarginRequest)(nil),                // 3: mizar.portfolio.GetMarginRequest
	(*GetMarginResponse)(nil),               // 4: mizar.portfolio.GetMarginResponse
	(*GetFuturePositionListRequest)(nil),    // 5: mizar.portfolio.GetFuturePositionListRequest
	(*GetFuturePositionListResponse)(nil),   // 6: mizar.portfolio.GetFuturePositionListResponse
	(*GetFuturePositionDetailRequest)(nil),  // 7: mizar.portfolio.GetFuturePositionDetailRequest
	(*GetFuturePositionDetailResponse)(nil), // 8: mizar.portfolio.GetFuturePositionDetailResponse
	(Action)(0),                             // 9: mizar.common.Action
	(ErrorCode)(0),                          // 10: mizar.common.ErrorCode
}
var file_mizar_portfolio_proto_depIdxs = []int32{
	9,  // 0: mizar.portfolio.FuturePosition.direction:type_name -> mizar.common.Action
	9,  // 1: mizar.portfolio.FuturePositionDetail.direction:type_name -> mizar.common.Action
	0,  // 2: mizar.portfolio.GetMarginResponse.margin_info:type_name -> mizar.portfolio.MarginInfo
	10, // 3: mizar.portfolio.GetMarginResponse.error_code:type_name -> mizar.common.ErrorCode
	1,  // 4: mizar.portfolio.GetFuturePositionListResponse.future_positions:type_name -> mizar.portfolio.FuturePosition
	10, // 5: mizar.portfolio.GetFuturePositionListResponse.error_code:type_name -> mizar.common.ErrorCode
	2,  // 6: mizar.portfolio.GetFuturePositionDetailResponse.future_details:type_name -> mizar.portfolio.FuturePositionDetail
	10, // 7: mizar.portfolio.GetFuturePositionDetailResponse.error_code:type_name -> mizar.common.ErrorCode
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mizar_portfolio_proto_init() }
func file_mizar_portfolio_proto_init() {
	if File_mizar_portfolio_proto != nil {
		return
	}
	file_mizar_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mizar_portfolio_proto_rawDesc), len(file_mizar_portfolio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mizar_portfolio_proto_goTypes,
		DependencyIndexes: file_mizar_portfolio_proto_depIdxs,
		MessageInfos:      file_mizar_portfolio_proto_msgTypes,
	}.Build()
	File_mizar_portfolio_proto = out.File
	file_mizar_portfolio_proto_goTypes = nil
	file_mizar_portfolio_proto_depIdxs = nil
}
