// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: mizar_trade.proto

package mizar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 期貨下單請求
type FuturePlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                         // 商品代碼
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                     // 商品符號
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`                                                     // 價格
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                                                // 委託數量
	Action        Action                 `protobuf:"varint,5,opt,name=action,proto3,enum=mizar.common.Action" json:"action,omitempty"`                           // 買賣方向
	PriceType     PriceType              `protobuf:"varint,6,opt,name=price_type,json=priceType,proto3,enum=mizar.common.PriceType" json:"price_type,omitempty"` // 價格類型
	OrderType     OrderType              `protobuf:"varint,7,opt,name=order_type,json=orderType,proto3,enum=mizar.common.OrderType" json:"order_type,omitempty"` // 委託類別
	OcType        OcType                 `protobuf:"varint,8,opt,name=oc_type,json=ocType,proto3,enum=mizar.common.OcType" json:"oc_type,omitempty"`             // 委託性質
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuturePlaceOrderRequest) Reset() {
	*x = FuturePlaceOrderRequest{}
	mi := &file_mizar_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuturePlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturePlaceOrderRequest) ProtoMessage() {}

func (x *FuturePlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturePlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*FuturePlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{0}
}

func (x *FuturePlaceOrderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FuturePlaceOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FuturePlaceOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FuturePlaceOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *FuturePlaceOrderRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *FuturePlaceOrderRequest) GetPriceType() PriceType {
	if x != nil {
		return x.PriceType
	}
	return PriceType_PRICE_TYPE_UNSPECIFIED
}

func (x *FuturePlaceOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *FuturePlaceOrderRequest) GetOcType() OcType {
	if x != nil {
		return x.OcType
	}
	return OcType_OC_TYPE_UNSPECIFIED
}

// 期貨下單回應
type FuturePlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *Trade                 `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`                                                       // 完整的委託交易資訊
	ErrorCode     ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuturePlaceOrderResponse) Reset() {
	*x = FuturePlaceOrderResponse{}
	mi := &file_mizar_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuturePlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturePlaceOrderResponse) ProtoMessage() {}

func (x *FuturePlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturePlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*FuturePlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{1}
}

func (x *FuturePlaceOrderResponse) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

func (x *FuturePlaceOrderResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *FuturePlaceOrderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 期貨改單請求
type FutureUpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                    // 委託單號
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`                                                     // 新價格
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                                // 新委託數量
	PriceType     PriceType              `protobuf:"varint,4,opt,name=price_type,json=priceType,proto3,enum=mizar.common.PriceType" json:"price_type,omitempty"` // 新價格類型
	OrderType     OrderType              `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=mizar.common.OrderType" json:"order_type,omitempty"` // 新委託類別
	OcType        OcType                 `protobuf:"varint,6,opt,name=oc_type,json=ocType,proto3,enum=mizar.common.OcType" json:"oc_type,omitempty"`             // 新委託性質
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FutureUpdateOrderRequest) Reset() {
	*x = FutureUpdateOrderRequest{}
	mi := &file_mizar_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureUpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureUpdateOrderRequest) ProtoMessage() {}

func (x *FutureUpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureUpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*FutureUpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{2}
}

func (x *FutureUpdateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *FutureUpdateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FutureUpdateOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *FutureUpdateOrderRequest) GetPriceType() PriceType {
	if x != nil {
		return x.PriceType
	}
	return PriceType_PRICE_TYPE_UNSPECIFIED
}

func (x *FutureUpdateOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *FutureUpdateOrderRequest) GetOcType() OcType {
	if x != nil {
		return x.OcType
	}
	return OcType_OC_TYPE_UNSPECIFIED
}

// 期貨改單回應
type FutureUpdateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *Trade                 `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`                                                       // 更新後的委託交易資訊
	ErrorCode     ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FutureUpdateOrderResponse) Reset() {
	*x = FutureUpdateOrderResponse{}
	mi := &file_mizar_trade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureUpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureUpdateOrderResponse) ProtoMessage() {}

func (x *FutureUpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureUpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*FutureUpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{3}
}

func (x *FutureUpdateOrderResponse) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

func (x *FutureUpdateOrderResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *FutureUpdateOrderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 期貨刪單請求
type FutureCancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 委託單號
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FutureCancelOrderRequest) Reset() {
	*x = FutureCancelOrderRequest{}
	mi := &file_mizar_trade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureCancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureCancelOrderRequest) ProtoMessage() {}

func (x *FutureCancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureCancelOrderRequest.ProtoReflect.Descriptor instead.
func (*FutureCancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{4}
}

func (x *FutureCancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 期貨刪單回應
type FutureCancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *Trade                 `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`                                                       // 刪單後的委託交易資訊
	ErrorCode     ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FutureCancelOrderResponse) Reset() {
	*x = FutureCancelOrderResponse{}
	mi := &file_mizar_trade_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureCancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureCancelOrderResponse) ProtoMessage() {}

func (x *FutureCancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureCancelOrderResponse.ProtoReflect.Descriptor instead.
func (*FutureCancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{5}
}

func (x *FutureCancelOrderResponse) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

func (x *FutureCancelOrderResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *FutureCancelOrderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 取得委託狀態請求
type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_mizar_trade_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{6}
}

// 取得委託狀態回應
type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`                                                     // 委託交易列表
	ErrorCode     ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=mizar.common.ErrorCode" json:"error_code,omitempty"` // 錯誤代碼
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                     // 錯誤訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_mizar_trade_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mizar_trade_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_mizar_trade_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderStatusResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *GetOrderStatusResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *GetOrderStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_mizar_trade_proto protoreflect.FileDescriptor

const file_mizar_trade_proto_rawDesc = "" +
	"\n" +
	"\x11mizar_trade.proto\x12\vmizar.trade\x1a\x12mizar_common.proto\"\xc4\x02\n" +
	"\x17FuturePlaceOrderRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12,\n" +
	"\x06action\x18\x05 \x01(\x0e2\x14.mizar.common.ActionR\x06action\x126\n" +
	"\n" +
	"price_type\x18\x06 \x01(\x0e2\x17.mizar.common.PriceTypeR\tpriceType\x126\n" +
	"\n" +
	"order_type\x18\a \x01(\x0e2\x17.mizar.common.OrderTypeR\torderType\x12-\n" +
	"\aoc_type\x18\b \x01(\x0e2\x14.mizar.common.OcTypeR\x06ocType\"\xa2\x01\n" +
	"\x18FuturePlaceOrderResponse\x12)\n" +
	"\x05trade\x18\x01 \x01(\v2\x13.mizar.common.TradeR\x05trade\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x86\x02\n" +
	"\x18FutureUpdateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x126\n" +
	"\n" +
	"price_type\x18\x04 \x01(\x0e2\x17.mizar.common.PriceTypeR\tpriceType\x126\n" +
	"\n" +
	"order_type\x18\x05 \x01(\x0e2\x17.mizar.common.OrderTypeR\torderType\x12-\n" +
	"\aoc_type\x18\x06 \x01(\x0e2\x14.mizar.common.OcTypeR\x06ocType\"\xa3\x01\n" +
	"\x19FutureUpdateOrderResponse\x12)\n" +
	"\x05trade\x18\x01 \x01(\v2\x13.mizar.common.TradeR\x05trade\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"5\n" +
	"\x18FutureCancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xa3\x01\n" +
	"\x19FutureCancelOrderResponse\x12)\n" +
	"\x05trade\x18\x01 \x01(\v2\x13.mizar.common.TradeR\x05trade\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x17\n" +
	"\x15GetOrderStatusRequest\"\xa2\x01\n" +
	"\x16GetOrderStatusResponse\x12+\n" +
	"\x06trades\x18\x01 \x03(\v2\x13.mizar.common.TradeR\x06trades\x126\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x17.mizar.common.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessageB*Z(github.com/mizar/mizar-proto/proto/mizarb\x06proto3"

var (
	file_mizar_trade_proto_rawDescOnce sync.Once
	file_mizar_trade_proto_rawDescData []byte
)

func file_mizar_trade_proto_rawDescGZIP() []byte {
	file_mizar_trade_proto_rawDescOnce.Do(func() {
		file_mizar_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mizar_trade_proto_rawDesc), len(file_mizar_trade_proto_rawDesc)))
	})
	return file_mizar_trade_proto_rawDescData
}

var file_mizar_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mizar_trade_proto_goTypes = []any{
	(*FuturePlaceOrderRequest)(nil),   // 0: mizar.trade.FuturePlaceOrderRequest
	(*FuturePlaceOrderResponse)(nil),  // 1: mizar.trade.FuturePlaceOrderResponse
	(*FutureUpdateOrderRequest)(nil),  // 2: mizar.trade.FutureUpdateOrderRequest
	(*FutureUpdateOrderResponse)(nil), // 3: mizar.trade.FutureUpdateOrderResponse
	(*FutureCancelOrderRequest)(nil),  // 4: mizar.trade.FutureCancelOrderRequest
	(*FutureCancelOrderResponse)(nil), // 5: mizar.trade.FutureCancelOrderResponse
	(*GetOrderStatusRequest)(nil),     // 6: mizar.trade.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil),    // 7: mizar.trade.GetOrderStatusResponse
	(Action)(0),                       // 8: mizar.common.Action
	(PriceType)(0),                    // 9: mizar.common.PriceType
	(OrderType)(0),                    // 10: mizar.common.OrderType
	(OcType)(0),                       // 11: mizar.common.OcType
	(*Trade)(nil),                     // 12: mizar.common.Trade
	(ErrorCode)(0),                    // 13: mizar.common.ErrorCode
}
var file_mizar_trade_proto_depIdxs = []int32{
	8,  // 0: mizar.trade.FuturePlaceOrderRequest.action:type_name -> mizar.common.Action
	9,  // 1: mizar.trade.FuturePlaceOrderRequest.price_type:type_name -> mizar.common.PriceType
	10, // 2: mizar.trade.FuturePlaceOrderRequest.order_type:type_name -> mizar.common.OrderType
	11, // 3: mizar.trade.FuturePlaceOrderRequest.oc_type:type_name -> mizar.common.OcType
	12, // 4: mizar.trade.FuturePlaceOrderResponse.trade:type_name -> mizar.common.Trade
	13, // 5: mizar.trade.FuturePlaceOrderResponse.error_code:type_name -> mizar.common.ErrorCode
	9,  // 6: mizar.trade.FutureUpdateOrderRequest.price_type:type_name -> mizar.common.PriceType
	10, // 7: mizar.trade.FutureUpdateOrderRequest.order_type:type_name -> mizar.common.OrderType
	11, // 8: mizar.trade.FutureUpdateOrderRequest.oc_type:type_name -> mizar.common.OcType
	12, // 9: mizar.trade.FutureUpdateOrderResponse.trade:type_name -> mizar.common.Trade
	13, // 10: mizar.trade.FutureUpdateOrderResponse.error_code:type_name -> mizar.common.ErrorCode
	12, // 11: mizar.trade.FutureCancelOrderResponse.trade:type_name -> mizar.common.Trade
	13, // 12: mizar.trade.FutureCancelOrderResponse.error_code:type_name -> mizar.common.ErrorCode
	12, // 13: mizar.trade.GetOrderStatusResponse.trades:type_name -> mizar.common.Trade
	13, // 14: mizar.trade.GetOrderStatusResponse.error_code:type_name -> mizar.common.ErrorCode
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_mizar_trade_proto_init() }
func file_mizar_trade_proto_init() {
	if File_mizar_trade_proto != nil {
		return
	}
	file_mizar_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mizar_trade_proto_rawDesc), len(file_mizar_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mizar_trade_proto_goTypes,
		DependencyIndexes: file_mizar_trade_proto_depIdxs,
		MessageInfos:      file_mizar_trade_proto_msgTypes,
	}.Build()
	File_mizar_trade_proto = out.File
	file_mizar_trade_proto_goTypes = nil
	file_mizar_trade_proto_depIdxs = nil
}
