"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import mizar_common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Exchange:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ExchangeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Exchange.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EXCHANGE_UNSPECIFIED: _Exchange.ValueType  # 0
    """未指定"""
    EXCHANGE_TSE: _Exchange.ValueType  # 1
    """台灣證券交易所"""
    EXCHANGE_OTC: _Exchange.ValueType  # 2
    """櫃買中心"""
    EXCHANGE_OES: _Exchange.ValueType  # 3
    """興櫃"""

class Exchange(_Exchange, metaclass=_ExchangeEnumTypeWrapper):
    """=============================================================================
    ENUM 定義區
    =============================================================================

    交易所類型
    """

EXCHANGE_UNSPECIFIED: Exchange.ValueType  # 0
"""未指定"""
EXCHANGE_TSE: Exchange.ValueType  # 1
"""台灣證券交易所"""
EXCHANGE_OTC: Exchange.ValueType  # 2
"""櫃買中心"""
EXCHANGE_OES: Exchange.ValueType  # 3
"""興櫃"""
global___Exchange = Exchange

class _DayTrade:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DayTradeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DayTrade.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DAY_TRADE_UNSPECIFIED: _DayTrade.ValueType  # 0
    """未指定"""
    DAY_TRADE_YES: _DayTrade.ValueType  # 1
    """可當沖"""
    DAY_TRADE_NO: _DayTrade.ValueType  # 2
    """不可當沖"""
    DAY_TRADE_ONLY_BUY: _DayTrade.ValueType  # 3
    """僅可買入當沖"""

class DayTrade(_DayTrade, metaclass=_DayTradeEnumTypeWrapper):
    """當沖類型"""

DAY_TRADE_UNSPECIFIED: DayTrade.ValueType  # 0
"""未指定"""
DAY_TRADE_YES: DayTrade.ValueType  # 1
"""可當沖"""
DAY_TRADE_NO: DayTrade.ValueType  # 2
"""不可當沖"""
DAY_TRADE_ONLY_BUY: DayTrade.ValueType  # 3
"""僅可買入當沖"""
global___DayTrade = DayTrade

class _OptionRight:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OptionRightEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OptionRight.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPTION_RIGHT_UNSPECIFIED: _OptionRight.ValueType  # 0
    """未指定"""
    OPTION_RIGHT_CALL: _OptionRight.ValueType  # 1
    """買權"""
    OPTION_RIGHT_PUT: _OptionRight.ValueType  # 2
    """賣權"""

class OptionRight(_OptionRight, metaclass=_OptionRightEnumTypeWrapper):
    """選擇權權利類型"""

OPTION_RIGHT_UNSPECIFIED: OptionRight.ValueType  # 0
"""未指定"""
OPTION_RIGHT_CALL: OptionRight.ValueType  # 1
"""買權"""
OPTION_RIGHT_PUT: OptionRight.ValueType  # 2
"""賣權"""
global___OptionRight = OptionRight

class _ContractType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ContractTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ContractType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONTRACT_TYPE_UNSPECIFIED: _ContractType.ValueType  # 0
    """未指定"""
    CONTRACT_TYPE_STOCK: _ContractType.ValueType  # 1
    """證券"""
    CONTRACT_TYPE_FUTURE: _ContractType.ValueType  # 2
    """期貨"""
    CONTRACT_TYPE_OPTION: _ContractType.ValueType  # 3
    """選擇權"""
    CONTRACT_TYPE_INDEX: _ContractType.ValueType  # 4
    """指數"""

class ContractType(_ContractType, metaclass=_ContractTypeEnumTypeWrapper):
    """合約類型"""

CONTRACT_TYPE_UNSPECIFIED: ContractType.ValueType  # 0
"""未指定"""
CONTRACT_TYPE_STOCK: ContractType.ValueType  # 1
"""證券"""
CONTRACT_TYPE_FUTURE: ContractType.ValueType  # 2
"""期貨"""
CONTRACT_TYPE_OPTION: ContractType.ValueType  # 3
"""選擇權"""
CONTRACT_TYPE_INDEX: ContractType.ValueType  # 4
"""指數"""
global___ContractType = ContractType

@typing.final
class FutureAccount(google.protobuf.message.Message):
    """=============================================================================
    一般 MESSAGE 定義區
    =============================================================================

    期貨帳號資訊
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PERSON_ID_FIELD_NUMBER: builtins.int
    BROKER_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    SIGNED_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    person_id: builtins.str
    """個人識別碼"""
    broker_id: builtins.str
    """券商識別碼"""
    account_id: builtins.str
    """帳號識別碼"""
    signed: builtins.bool
    """是否已簽署"""
    username: builtins.str
    """使用者名稱"""
    def __init__(
        self,
        *,
        person_id: builtins.str = ...,
        broker_id: builtins.str = ...,
        account_id: builtins.str = ...,
        signed: builtins.bool = ...,
        username: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "broker_id", b"broker_id", "person_id", b"person_id", "signed", b"signed", "username", b"username"]) -> None: ...

global___FutureAccount = FutureAccount

@typing.final
class Stock(google.protobuf.message.Message):
    """證券合約資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXCHANGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    LIMIT_UP_FIELD_NUMBER: builtins.int
    LIMIT_DOWN_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    MARGIN_TRADING_BALANCE_FIELD_NUMBER: builtins.int
    SHORT_SELLING_BALANCE_FIELD_NUMBER: builtins.int
    DAY_TRADE_FIELD_NUMBER: builtins.int
    exchange: global___Exchange.ValueType
    """交易所"""
    code: builtins.str
    """商品代碼"""
    symbol: builtins.str
    """符號"""
    name: builtins.str
    """商品名稱"""
    category: builtins.str
    """類別"""
    unit: builtins.int
    """單位"""
    limit_up: builtins.float
    """漲停價"""
    limit_down: builtins.float
    """跌停價"""
    reference: builtins.float
    """參考價"""
    update_date: builtins.str
    """更新日期"""
    margin_trading_balance: builtins.int
    """融資餘額"""
    short_selling_balance: builtins.int
    """融券餘額"""
    day_trade: global___DayTrade.ValueType
    """可否當沖"""
    def __init__(
        self,
        *,
        exchange: global___Exchange.ValueType = ...,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
        category: builtins.str = ...,
        unit: builtins.int = ...,
        limit_up: builtins.float = ...,
        limit_down: builtins.float = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
        margin_trading_balance: builtins.int = ...,
        short_selling_balance: builtins.int = ...,
        day_trade: global___DayTrade.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "day_trade", b"day_trade", "exchange", b"exchange", "limit_down", b"limit_down", "limit_up", b"limit_up", "margin_trading_balance", b"margin_trading_balance", "name", b"name", "reference", b"reference", "short_selling_balance", b"short_selling_balance", "symbol", b"symbol", "unit", b"unit", "update_date", b"update_date"]) -> None: ...

global___Stock = Stock

@typing.final
class Future(google.protobuf.message.Message):
    """期貨合約資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    DELIVERY_MONTH_FIELD_NUMBER: builtins.int
    DELIVERY_DATE_FIELD_NUMBER: builtins.int
    UNDERLYING_KIND_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    LIMIT_UP_FIELD_NUMBER: builtins.int
    LIMIT_DOWN_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    code: builtins.str
    """商品代碼"""
    symbol: builtins.str
    """符號"""
    name: builtins.str
    """商品名稱"""
    category: builtins.str
    """類別"""
    delivery_month: builtins.str
    """交割月份"""
    delivery_date: builtins.str
    """結算日"""
    underlying_kind: builtins.str
    """標的類型"""
    unit: builtins.int
    """單位"""
    limit_up: builtins.float
    """漲停價"""
    limit_down: builtins.float
    """跌停價"""
    reference: builtins.float
    """參考價"""
    update_date: builtins.str
    """更新時間"""
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
        category: builtins.str = ...,
        delivery_month: builtins.str = ...,
        delivery_date: builtins.str = ...,
        underlying_kind: builtins.str = ...,
        unit: builtins.int = ...,
        limit_up: builtins.float = ...,
        limit_down: builtins.float = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "delivery_date", b"delivery_date", "delivery_month", b"delivery_month", "limit_down", b"limit_down", "limit_up", b"limit_up", "name", b"name", "reference", b"reference", "symbol", b"symbol", "underlying_kind", b"underlying_kind", "unit", b"unit", "update_date", b"update_date"]) -> None: ...

global___Future = Future

@typing.final
class Option(google.protobuf.message.Message):
    """選擇權合約資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    DELIVERY_MONTH_FIELD_NUMBER: builtins.int
    DELIVERY_DATE_FIELD_NUMBER: builtins.int
    STRIKE_PRICE_FIELD_NUMBER: builtins.int
    OPTION_RIGHT_FIELD_NUMBER: builtins.int
    UNDERLYING_KIND_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    LIMIT_UP_FIELD_NUMBER: builtins.int
    LIMIT_DOWN_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    code: builtins.str
    """商品代碼"""
    symbol: builtins.str
    """符號"""
    name: builtins.str
    """商品名稱"""
    category: builtins.str
    """類型"""
    delivery_month: builtins.str
    """交割月份"""
    delivery_date: builtins.str
    """交割日期"""
    strike_price: builtins.float
    """履約價"""
    option_right: global___OptionRight.ValueType
    """買賣權別"""
    underlying_kind: builtins.str
    """標的類型"""
    unit: builtins.int
    """單位"""
    limit_up: builtins.float
    """漲停價"""
    limit_down: builtins.float
    """跌停價"""
    reference: builtins.float
    """參考價"""
    update_date: builtins.str
    """更新時間"""
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
        category: builtins.str = ...,
        delivery_month: builtins.str = ...,
        delivery_date: builtins.str = ...,
        strike_price: builtins.float = ...,
        option_right: global___OptionRight.ValueType = ...,
        underlying_kind: builtins.str = ...,
        unit: builtins.int = ...,
        limit_up: builtins.float = ...,
        limit_down: builtins.float = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "delivery_date", b"delivery_date", "delivery_month", b"delivery_month", "limit_down", b"limit_down", "limit_up", b"limit_up", "name", b"name", "option_right", b"option_right", "reference", b"reference", "strike_price", b"strike_price", "symbol", b"symbol", "underlying_kind", b"underlying_kind", "unit", b"unit", "update_date", b"update_date"]) -> None: ...

global___Option = Option

@typing.final
class Index(google.protobuf.message.Message):
    """指數合約資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXCHANGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    exchange: global___Exchange.ValueType
    """交易所"""
    code: builtins.str
    """商品代碼"""
    symbol: builtins.str
    """符號"""
    name: builtins.str
    """商品名稱"""
    def __init__(
        self,
        *,
        exchange: global___Exchange.ValueType = ...,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "exchange", b"exchange", "name", b"name", "symbol", b"symbol"]) -> None: ...

global___Index = Index

@typing.final
class ContractCollection(google.protobuf.message.Message):
    """合約資訊集合"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOCKS_FIELD_NUMBER: builtins.int
    FUTURES_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    INDEXES_FIELD_NUMBER: builtins.int
    @property
    def stocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Stock]:
        """證券合約列表"""

    @property
    def futures(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Future]:
        """期貨合約列表"""

    @property
    def options(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Option]:
        """選擇權合約列表"""

    @property
    def indexes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Index]:
        """指數合約列表"""

    def __init__(
        self,
        *,
        stocks: collections.abc.Iterable[global___Stock] | None = ...,
        futures: collections.abc.Iterable[global___Future] | None = ...,
        options: collections.abc.Iterable[global___Option] | None = ...,
        indexes: collections.abc.Iterable[global___Index] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["futures", b"futures", "indexes", b"indexes", "options", b"options", "stocks", b"stocks"]) -> None: ...

global___ContractCollection = ContractCollection

@typing.final
class GetFutureAccountRequest(google.protobuf.message.Message):
    """=============================================================================
    MQ 使用 MESSAGE 定義區
    =============================================================================

    取得期貨預設帳號請求
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetFutureAccountRequest = GetFutureAccountRequest

@typing.final
class GetFutureAccountResponse(google.protobuf.message.Message):
    """取得期貨預設帳號回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def account(self) -> global___FutureAccount:
        """期貨帳號資訊"""

    def __init__(
        self,
        *,
        account: global___FutureAccount | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "error_code", b"error_code", "error_message", b"error_message"]) -> None: ...

global___GetFutureAccountResponse = GetFutureAccountResponse

@typing.final
class GetContractRequest(google.protobuf.message.Message):
    """取得合約資訊請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_TYPE_FIELD_NUMBER: builtins.int
    contract_type: global___ContractType.ValueType
    """合約類型（可選，不指定則取得全部）"""
    def __init__(
        self,
        *,
        contract_type: global___ContractType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_type", b"contract_type"]) -> None: ...

global___GetContractRequest = GetContractRequest

@typing.final
class GetContractResponse(google.protobuf.message.Message):
    """取得合約資訊回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACTS_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def contracts(self) -> global___ContractCollection:
        """合約資訊集合"""

    def __init__(
        self,
        *,
        contracts: global___ContractCollection | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["contracts", b"contracts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["contracts", b"contracts", "error_code", b"error_code", "error_message", b"error_message"]) -> None: ...

global___GetContractResponse = GetContractResponse
