# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mizar_trade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mizar_trade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mizar_common_pb2 as mizar__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mizar_trade.proto\x12\x0bmizar.trade\x1a\x12mizar_common.proto\"\xff\x01\n\x17\x46uturePlaceOrderRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x03\x12$\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32\x14.mizar.common.Action\x12+\n\nprice_type\x18\x06 \x01(\x0e\x32\x17.mizar.common.PriceType\x12+\n\norder_type\x18\x07 \x01(\x0e\x32\x17.mizar.common.OrderType\x12%\n\x07oc_type\x18\x08 \x01(\x0e\x32\x14.mizar.common.OcType\"\x82\x01\n\x18\x46uturePlaceOrderResponse\x12\"\n\x05trade\x18\x01 \x01(\x0b\x32\x13.mizar.common.Trade\x12+\n\nerror_code\x18\x02 \x01(\x0e\x32\x17.mizar.common.ErrorCode\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\xce\x01\n\x18\x46utureUpdateOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x03\x12+\n\nprice_type\x18\x04 \x01(\x0e\x32\x17.mizar.common.PriceType\x12+\n\norder_type\x18\x05 \x01(\x0e\x32\x17.mizar.common.OrderType\x12%\n\x07oc_type\x18\x06 \x01(\x0e\x32\x14.mizar.common.OcType\"\x83\x01\n\x19\x46utureUpdateOrderResponse\x12\"\n\x05trade\x18\x01 \x01(\x0b\x32\x13.mizar.common.Trade\x12+\n\nerror_code\x18\x02 \x01(\x0e\x32\x17.mizar.common.ErrorCode\x12\x15\n\rerror_message\x18\x03 \x01(\t\",\n\x18\x46utureCancelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x83\x01\n\x19\x46utureCancelOrderResponse\x12\"\n\x05trade\x18\x01 \x01(\x0b\x32\x13.mizar.common.Trade\x12+\n\nerror_code\x18\x02 \x01(\x0e\x32\x17.mizar.common.ErrorCode\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x17\n\x15GetOrderStatusRequest\"\x81\x01\n\x16GetOrderStatusResponse\x12#\n\x06trades\x18\x01 \x03(\x0b\x32\x13.mizar.common.Trade\x12+\n\nerror_code\x18\x02 \x01(\x0e\x32\x17.mizar.common.ErrorCode\x12\x15\n\rerror_message\x18\x03 \x01(\tB*Z(github.com/mizar/mizar-proto/proto/mizarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mizar_trade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/mizar/mizar-proto/proto/mizar'
  _globals['_FUTUREPLACEORDERREQUEST']._serialized_start=55
  _globals['_FUTUREPLACEORDERREQUEST']._serialized_end=310
  _globals['_FUTUREPLACEORDERRESPONSE']._serialized_start=313
  _globals['_FUTUREPLACEORDERRESPONSE']._serialized_end=443
  _globals['_FUTUREUPDATEORDERREQUEST']._serialized_start=446
  _globals['_FUTUREUPDATEORDERREQUEST']._serialized_end=652
  _globals['_FUTUREUPDATEORDERRESPONSE']._serialized_start=655
  _globals['_FUTUREUPDATEORDERRESPONSE']._serialized_end=786
  _globals['_FUTURECANCELORDERREQUEST']._serialized_start=788
  _globals['_FUTURECANCELORDERREQUEST']._serialized_end=832
  _globals['_FUTURECANCELORDERRESPONSE']._serialized_start=835
  _globals['_FUTURECANCELORDERRESPONSE']._serialized_end=966
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=968
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=991
  _globals['_GETORDERSTATUSRESPONSE']._serialized_start=994
  _globals['_GETORDERSTATUSRESPONSE']._serialized_end=1123
# @@protoc_insertion_point(module_scope)
