"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import mizar_common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _QuoteType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _QuoteTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QuoteType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUOTE_TYPE_UNSPECIFIED: _QuoteType.ValueType  # 0
    """未指定"""
    QUOTE_TYPE_TICK: _QuoteType.ValueType  # 1
    """逐筆資料"""
    QUOTE_TYPE_BIDASK: _QuoteType.ValueType  # 2
    """買賣價量"""
    QUOTE_TYPE_QUOTE: _QuoteType.ValueType  # 3
    """整股報價"""

class QuoteType(_QuoteType, metaclass=_QuoteTypeEnumTypeWrapper):
    """=============================================================================
    ENUM 定義區
    =============================================================================

    報價類型
    """

QUOTE_TYPE_UNSPECIFIED: QuoteType.ValueType  # 0
"""未指定"""
QUOTE_TYPE_TICK: QuoteType.ValueType  # 1
"""逐筆資料"""
QUOTE_TYPE_BIDASK: QuoteType.ValueType  # 2
"""買賣價量"""
QUOTE_TYPE_QUOTE: QuoteType.ValueType  # 3
"""整股報價"""
global___QuoteType = QuoteType

@typing.final
class TickDataList(google.protobuf.message.Message):
    """=============================================================================
    一般 MESSAGE 定義區
    =============================================================================

    TICK 資料陣列格式
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMPS_FIELD_NUMBER: builtins.int
    CLOSE_PRICES_FIELD_NUMBER: builtins.int
    VOLUMES_FIELD_NUMBER: builtins.int
    BID_PRICES_FIELD_NUMBER: builtins.int
    BID_VOLUMES_FIELD_NUMBER: builtins.int
    ASK_PRICES_FIELD_NUMBER: builtins.int
    ASK_VOLUMES_FIELD_NUMBER: builtins.int
    TICK_TYPES_FIELD_NUMBER: builtins.int
    @property
    def timestamps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """納秒時間戳陣列"""

    @property
    def close_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """成交價陣列"""

    @property
    def volumes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """成交量陣列"""

    @property
    def bid_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """買價陣列"""

    @property
    def bid_volumes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """買量陣列"""

    @property
    def ask_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """賣價陣列"""

    @property
    def ask_volumes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """賣量陣列"""

    @property
    def tick_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """TICK 類型陣列"""

    def __init__(
        self,
        *,
        timestamps: collections.abc.Iterable[builtins.int] | None = ...,
        close_prices: collections.abc.Iterable[builtins.float] | None = ...,
        volumes: collections.abc.Iterable[builtins.int] | None = ...,
        bid_prices: collections.abc.Iterable[builtins.float] | None = ...,
        bid_volumes: collections.abc.Iterable[builtins.int] | None = ...,
        ask_prices: collections.abc.Iterable[builtins.float] | None = ...,
        ask_volumes: collections.abc.Iterable[builtins.int] | None = ...,
        tick_types: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ask_prices", b"ask_prices", "ask_volumes", b"ask_volumes", "bid_prices", b"bid_prices", "bid_volumes", b"bid_volumes", "close_prices", b"close_prices", "tick_types", b"tick_types", "timestamps", b"timestamps", "volumes", b"volumes"]) -> None: ...

global___TickDataList = TickDataList

@typing.final
class KbarDataList(google.protobuf.message.Message):
    """KBAR 資料陣列格式"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMPS_FIELD_NUMBER: builtins.int
    OPEN_PRICES_FIELD_NUMBER: builtins.int
    HIGH_PRICES_FIELD_NUMBER: builtins.int
    LOW_PRICES_FIELD_NUMBER: builtins.int
    CLOSE_PRICES_FIELD_NUMBER: builtins.int
    VOLUMES_FIELD_NUMBER: builtins.int
    @property
    def timestamps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """納秒時間戳陣列"""

    @property
    def open_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """開盤價陣列"""

    @property
    def high_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """最高價陣列"""

    @property
    def low_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """最低價陣列"""

    @property
    def close_prices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """收盤價陣列"""

    @property
    def volumes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """成交量陣列"""

    def __init__(
        self,
        *,
        timestamps: collections.abc.Iterable[builtins.int] | None = ...,
        open_prices: collections.abc.Iterable[builtins.float] | None = ...,
        high_prices: collections.abc.Iterable[builtins.float] | None = ...,
        low_prices: collections.abc.Iterable[builtins.float] | None = ...,
        close_prices: collections.abc.Iterable[builtins.float] | None = ...,
        volumes: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["close_prices", b"close_prices", "high_prices", b"high_prices", "low_prices", b"low_prices", "open_prices", b"open_prices", "timestamps", b"timestamps", "volumes", b"volumes"]) -> None: ...

global___KbarDataList = KbarDataList

@typing.final
class MarketSnapshotData(google.protobuf.message.Message):
    """市場快照資料"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    CHANGE_PRICE_FIELD_NUMBER: builtins.int
    CHANGE_RATE_FIELD_NUMBER: builtins.int
    AVERAGE_PRICE_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    TOTAL_VOLUME_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    TOTAL_AMOUNT_FIELD_NUMBER: builtins.int
    YESTERDAY_VOLUME_FIELD_NUMBER: builtins.int
    BUY_PRICE_FIELD_NUMBER: builtins.int
    BUY_VOLUME_FIELD_NUMBER: builtins.int
    SELL_PRICE_FIELD_NUMBER: builtins.int
    SELL_VOLUME_FIELD_NUMBER: builtins.int
    VOLUME_RATIO_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    """時間戳"""
    contract_code: builtins.str
    """合約代碼"""
    open: builtins.float
    """開盤價"""
    high: builtins.float
    """最高價"""
    low: builtins.float
    """最低價"""
    close: builtins.float
    """收盤價"""
    change_price: builtins.float
    """漲跌"""
    change_rate: builtins.float
    """漲跌幅"""
    average_price: builtins.float
    """均價"""
    volume: builtins.int
    """成交量"""
    total_volume: builtins.int
    """總成交量"""
    amount: builtins.int
    """成交金額"""
    total_amount: builtins.int
    """總成交金額"""
    yesterday_volume: builtins.float
    """昨量"""
    buy_price: builtins.float
    """委買價"""
    buy_volume: builtins.float
    """委買量"""
    sell_price: builtins.float
    """委賣價"""
    sell_volume: builtins.int
    """委賣量"""
    volume_ratio: builtins.float
    """量比"""
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
        contract_code: builtins.str = ...,
        open: builtins.float = ...,
        high: builtins.float = ...,
        low: builtins.float = ...,
        close: builtins.float = ...,
        change_price: builtins.float = ...,
        change_rate: builtins.float = ...,
        average_price: builtins.float = ...,
        volume: builtins.int = ...,
        total_volume: builtins.int = ...,
        amount: builtins.int = ...,
        total_amount: builtins.int = ...,
        yesterday_volume: builtins.float = ...,
        buy_price: builtins.float = ...,
        buy_volume: builtins.float = ...,
        sell_price: builtins.float = ...,
        sell_volume: builtins.int = ...,
        volume_ratio: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "average_price", b"average_price", "buy_price", b"buy_price", "buy_volume", b"buy_volume", "change_price", b"change_price", "change_rate", b"change_rate", "close", b"close", "contract_code", b"contract_code", "high", b"high", "low", b"low", "open", b"open", "sell_price", b"sell_price", "sell_volume", b"sell_volume", "timestamp", b"timestamp", "total_amount", b"total_amount", "total_volume", b"total_volume", "volume", b"volume", "volume_ratio", b"volume_ratio", "yesterday_volume", b"yesterday_volume"]) -> None: ...

global___MarketSnapshotData = MarketSnapshotData

@typing.final
class ShortStockSourceData(google.protobuf.message.Message):
    """或有券源資料"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    SHORT_STOCK_SOURCE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    contract_code: builtins.str
    """合約代碼"""
    short_stock_source: builtins.float
    """或有券源數量"""
    timestamp: builtins.int
    """時間戳"""
    def __init__(
        self,
        *,
        contract_code: builtins.str = ...,
        short_stock_source: builtins.float = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_code", b"contract_code", "short_stock_source", b"short_stock_source", "timestamp", b"timestamp"]) -> None: ...

global___ShortStockSourceData = ShortStockSourceData

@typing.final
class CreditEnquireData(google.protobuf.message.Message):
    """資券餘額資料"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    SYSTEM_FIELD_NUMBER: builtins.int
    MARGIN_UNIT_FIELD_NUMBER: builtins.int
    SHORT_UNIT_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    contract_code: builtins.str
    """合約代碼"""
    system: builtins.str
    """券商系統（HE/HC/HN/HF）- 含義不明"""
    margin_unit: builtins.int
    """融資餘額"""
    short_unit: builtins.int
    """融券餘額"""
    update_time: builtins.int
    """更新時間（納秒時間戳）"""
    def __init__(
        self,
        *,
        contract_code: builtins.str = ...,
        system: builtins.str = ...,
        margin_unit: builtins.int = ...,
        short_unit: builtins.int = ...,
        update_time: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_code", b"contract_code", "margin_unit", b"margin_unit", "short_unit", b"short_unit", "system", b"system", "update_time", b"update_time"]) -> None: ...

global___CreditEnquireData = CreditEnquireData

@typing.final
class SubscribeQuoteRequest(google.protobuf.message.Message):
    """=============================================================================
    MQ 使用 MESSAGE 定義區
    =============================================================================

    訂閱報價請求
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOL_FIELD_NUMBER: builtins.int
    QUOTE_TYPE_FIELD_NUMBER: builtins.int
    INTRADAY_ODD_FIELD_NUMBER: builtins.int
    contract_code: builtins.str
    """合約代碼（優先使用）"""
    contract_symbol: builtins.str
    """合約符號（未提供CODE時用這個）"""
    quote_type: global___QuoteType.ValueType
    """報價類型（預設為 TICK）"""
    intraday_odd: builtins.bool
    """是否包含盤中零股（預設為 false）"""
    def __init__(
        self,
        *,
        contract_code: builtins.str = ...,
        contract_symbol: builtins.str = ...,
        quote_type: global___QuoteType.ValueType = ...,
        intraday_odd: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_code", b"contract_code", "contract_symbol", b"contract_symbol", "intraday_odd", b"intraday_odd", "quote_type", b"quote_type"]) -> None: ...

global___SubscribeQuoteRequest = SubscribeQuoteRequest

@typing.final
class SubscribeQuoteResponse(google.protobuf.message.Message):
    """訂閱報價回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    def __init__(
        self,
        *,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message"]) -> None: ...

global___SubscribeQuoteResponse = SubscribeQuoteResponse

@typing.final
class UnsubscribeQuoteRequest(google.protobuf.message.Message):
    """取消訂閱報價請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOL_FIELD_NUMBER: builtins.int
    contract_code: builtins.str
    """合約代碼（優先使用）"""
    contract_symbol: builtins.str
    """合約符號（未提供CODE時用這個）"""
    def __init__(
        self,
        *,
        contract_code: builtins.str = ...,
        contract_symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_code", b"contract_code", "contract_symbol", b"contract_symbol"]) -> None: ...

global___UnsubscribeQuoteRequest = UnsubscribeQuoteRequest

@typing.final
class UnsubscribeQuoteResponse(google.protobuf.message.Message):
    """取消訂閱報價回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    def __init__(
        self,
        *,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message"]) -> None: ...

global___UnsubscribeQuoteResponse = UnsubscribeQuoteResponse

@typing.final
class GetHistoryTickRequest(google.protobuf.message.Message):
    """取得歷史 TICK 資料請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOL_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    contract_code: builtins.str
    """合約代碼（優先使用）"""
    contract_symbol: builtins.str
    """合約符號（未提供CODE時用這個）"""
    date: builtins.str
    """日期（YYYY-MM-DD）"""
    def __init__(
        self,
        *,
        contract_code: builtins.str = ...,
        contract_symbol: builtins.str = ...,
        date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_code", b"contract_code", "contract_symbol", b"contract_symbol", "date", b"date"]) -> None: ...

global___GetHistoryTickRequest = GetHistoryTickRequest

@typing.final
class GetHistoryTickResponse(google.protobuf.message.Message):
    """取得歷史 TICK 資料回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICK_DATA_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def tick_data(self) -> global___TickDataList:
        """TICK 資料陣列"""

    def __init__(
        self,
        *,
        tick_data: global___TickDataList | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tick_data", b"tick_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "tick_data", b"tick_data"]) -> None: ...

global___GetHistoryTickResponse = GetHistoryTickResponse

@typing.final
class GetHistoryKbarRequest(google.protobuf.message.Message):
    """取得歷史 KBAR 資料請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODE_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOL_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    contract_code: builtins.str
    """合約代碼（優先使用）"""
    contract_symbol: builtins.str
    """合約符號（未提供CODE時用這個）"""
    date: builtins.str
    """日期（YYYY-MM-DD）"""
    def __init__(
        self,
        *,
        contract_code: builtins.str = ...,
        contract_symbol: builtins.str = ...,
        date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_code", b"contract_code", "contract_symbol", b"contract_symbol", "date", b"date"]) -> None: ...

global___GetHistoryKbarRequest = GetHistoryKbarRequest

@typing.final
class GetHistoryKbarResponse(google.protobuf.message.Message):
    """取得歷史 KBAR 資料回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KBAR_DATA_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def kbar_data(self) -> global___KbarDataList:
        """KBAR 資料陣列"""

    def __init__(
        self,
        *,
        kbar_data: global___KbarDataList | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["kbar_data", b"kbar_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "kbar_data", b"kbar_data"]) -> None: ...

global___GetHistoryKbarResponse = GetHistoryKbarResponse

@typing.final
class GetMarketSnapshotRequest(google.protobuf.message.Message):
    """取得市場快照請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODES_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def contract_codes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """合約代碼列表（優先使用）"""

    @property
    def contract_symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """合約符號列表（未提供CODE時用這個）"""

    def __init__(
        self,
        *,
        contract_codes: collections.abc.Iterable[builtins.str] | None = ...,
        contract_symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_codes", b"contract_codes", "contract_symbols", b"contract_symbols"]) -> None: ...

global___GetMarketSnapshotRequest = GetMarketSnapshotRequest

@typing.final
class GetMarketSnapshotResponse(google.protobuf.message.Message):
    """取得市場快照回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SNAPSHOTS_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def snapshots(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MarketSnapshotData]:
        """快照資料列表"""

    def __init__(
        self,
        *,
        snapshots: collections.abc.Iterable[global___MarketSnapshotData] | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "snapshots", b"snapshots"]) -> None: ...

global___GetMarketSnapshotResponse = GetMarketSnapshotResponse

@typing.final
class GetShortStockSourceRequest(google.protobuf.message.Message):
    """取得或有券源請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODES_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def contract_codes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """合約代碼列表（優先使用）"""

    @property
    def contract_symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """合約符號列表（未提供CODE時用這個）"""

    def __init__(
        self,
        *,
        contract_codes: collections.abc.Iterable[builtins.str] | None = ...,
        contract_symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_codes", b"contract_codes", "contract_symbols", b"contract_symbols"]) -> None: ...

global___GetShortStockSourceRequest = GetShortStockSourceRequest

@typing.final
class GetShortStockSourceResponse(google.protobuf.message.Message):
    """取得或有券源回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCES_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def sources(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ShortStockSourceData]:
        """券源資料列表"""

    def __init__(
        self,
        *,
        sources: collections.abc.Iterable[global___ShortStockSourceData] | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "sources", b"sources"]) -> None: ...

global___GetShortStockSourceResponse = GetShortStockSourceResponse

@typing.final
class GetCreditEnquireRequest(google.protobuf.message.Message):
    """取得資券餘額請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_CODES_FIELD_NUMBER: builtins.int
    CONTRACT_SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def contract_codes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """合約代碼列表（優先使用）"""

    @property
    def contract_symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """合約符號列表（未提供CODE時用這個）"""

    def __init__(
        self,
        *,
        contract_codes: collections.abc.Iterable[builtins.str] | None = ...,
        contract_symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_codes", b"contract_codes", "contract_symbols", b"contract_symbols"]) -> None: ...

global___GetCreditEnquireRequest = GetCreditEnquireRequest

@typing.final
class GetCreditEnquireResponse(google.protobuf.message.Message):
    """取得資券餘額回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREDIT_DATA_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼（0=成功）"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def credit_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CreditEnquireData]:
        """資券餘額資料列表"""

    def __init__(
        self,
        *,
        credit_data: collections.abc.Iterable[global___CreditEnquireData] | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["credit_data", b"credit_data", "error_code", b"error_code", "error_message", b"error_message"]) -> None: ...

global___GetCreditEnquireResponse = GetCreditEnquireResponse
