"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import mizar_common_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MarginInfo(google.protobuf.message.Message):
    """=============================================================================
    一般 MESSAGE 定義區
    =============================================================================

    保證金資訊
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    YESTERDAY_BALANCE_FIELD_NUMBER: builtins.int
    TODAY_BALANCE_FIELD_NUMBER: builtins.int
    DEPOSIT_WITHDRAWAL_FIELD_NUMBER: builtins.int
    FEE_FIELD_NUMBER: builtins.int
    TAX_FIELD_NUMBER: builtins.int
    INITIAL_MARGIN_FIELD_NUMBER: builtins.int
    MAINTENANCE_MARGIN_FIELD_NUMBER: builtins.int
    MARGIN_CALL_FIELD_NUMBER: builtins.int
    RISK_INDICATOR_FIELD_NUMBER: builtins.int
    ROYALTY_REVENUE_EXPENDITURE_FIELD_NUMBER: builtins.int
    EQUITY_FIELD_NUMBER: builtins.int
    EQUITY_AMOUNT_FIELD_NUMBER: builtins.int
    OPTION_OPENBUY_MARKET_VALUE_FIELD_NUMBER: builtins.int
    OPTION_OPENSELL_MARKET_VALUE_FIELD_NUMBER: builtins.int
    OPTION_OPEN_POSITION_FIELD_NUMBER: builtins.int
    OPTION_SETTLE_PROFITLOSS_FIELD_NUMBER: builtins.int
    FUTURE_OPEN_POSITION_FIELD_NUMBER: builtins.int
    TODAY_FUTURE_OPEN_POSITION_FIELD_NUMBER: builtins.int
    FUTURE_SETTLE_PROFITLOSS_FIELD_NUMBER: builtins.int
    AVAILABLE_MARGIN_FIELD_NUMBER: builtins.int
    PLUS_MARGIN_FIELD_NUMBER: builtins.int
    PLUS_MARGIN_INDICATOR_FIELD_NUMBER: builtins.int
    SECURITY_COLLATERAL_AMOUNT_FIELD_NUMBER: builtins.int
    ORDER_MARGIN_PREMIUM_FIELD_NUMBER: builtins.int
    COLLATERAL_AMOUNT_FIELD_NUMBER: builtins.int
    yesterday_balance: builtins.float
    """前日餘額"""
    today_balance: builtins.float
    """今日餘額"""
    deposit_withdrawal: builtins.float
    """存提"""
    fee: builtins.float
    """手續費"""
    tax: builtins.float
    """期交稅"""
    initial_margin: builtins.float
    """原始保證金"""
    maintenance_margin: builtins.float
    """維持保證金"""
    margin_call: builtins.float
    """追繳保證金"""
    risk_indicator: builtins.float
    """風險指標"""
    royalty_revenue_expenditure: builtins.float
    """權利金收入與支出"""
    equity: builtins.float
    """權益數"""
    equity_amount: builtins.float
    """權益總值"""
    option_openbuy_market_value: builtins.float
    """未沖銷買方選擇權市值"""
    option_opensell_market_value: builtins.float
    """未沖銷賣方選擇權市值"""
    option_open_position: builtins.float
    """參考未平倉選擇權損益"""
    option_settle_profitloss: builtins.float
    """參考選擇權平倉損益"""
    future_open_position: builtins.float
    """未沖銷期貨浮動損益"""
    today_future_open_position: builtins.float
    """參考當日未沖銷期貨浮動損益"""
    future_settle_profitloss: builtins.float
    """期貨平倉損益"""
    available_margin: builtins.float
    """可動用(出金)保證金"""
    plus_margin: builtins.float
    """依「加收保證金指標」所加收之保證金"""
    plus_margin_indicator: builtins.float
    """加收保證金指標"""
    security_collateral_amount: builtins.float
    """有價證券抵繳總額"""
    order_margin_premium: builtins.float
    """委託保證金及委託權利金"""
    collateral_amount: builtins.float
    """有價品額"""
    def __init__(
        self,
        *,
        yesterday_balance: builtins.float = ...,
        today_balance: builtins.float = ...,
        deposit_withdrawal: builtins.float = ...,
        fee: builtins.float = ...,
        tax: builtins.float = ...,
        initial_margin: builtins.float = ...,
        maintenance_margin: builtins.float = ...,
        margin_call: builtins.float = ...,
        risk_indicator: builtins.float = ...,
        royalty_revenue_expenditure: builtins.float = ...,
        equity: builtins.float = ...,
        equity_amount: builtins.float = ...,
        option_openbuy_market_value: builtins.float = ...,
        option_opensell_market_value: builtins.float = ...,
        option_open_position: builtins.float = ...,
        option_settle_profitloss: builtins.float = ...,
        future_open_position: builtins.float = ...,
        today_future_open_position: builtins.float = ...,
        future_settle_profitloss: builtins.float = ...,
        available_margin: builtins.float = ...,
        plus_margin: builtins.float = ...,
        plus_margin_indicator: builtins.float = ...,
        security_collateral_amount: builtins.float = ...,
        order_margin_premium: builtins.float = ...,
        collateral_amount: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["available_margin", b"available_margin", "collateral_amount", b"collateral_amount", "deposit_withdrawal", b"deposit_withdrawal", "equity", b"equity", "equity_amount", b"equity_amount", "fee", b"fee", "future_open_position", b"future_open_position", "future_settle_profitloss", b"future_settle_profitloss", "initial_margin", b"initial_margin", "maintenance_margin", b"maintenance_margin", "margin_call", b"margin_call", "option_open_position", b"option_open_position", "option_openbuy_market_value", b"option_openbuy_market_value", "option_opensell_market_value", b"option_opensell_market_value", "option_settle_profitloss", b"option_settle_profitloss", "order_margin_premium", b"order_margin_premium", "plus_margin", b"plus_margin", "plus_margin_indicator", b"plus_margin_indicator", "risk_indicator", b"risk_indicator", "royalty_revenue_expenditure", b"royalty_revenue_expenditure", "security_collateral_amount", b"security_collateral_amount", "tax", b"tax", "today_balance", b"today_balance", "today_future_open_position", b"today_future_open_position", "yesterday_balance", b"yesterday_balance"]) -> None: ...

global___MarginInfo = MarginInfo

@typing.final
class FuturePosition(google.protobuf.message.Message):
    """期貨持倉資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    LAST_PRICE_FIELD_NUMBER: builtins.int
    PNL_FIELD_NUMBER: builtins.int
    id: builtins.int
    """部位代碼"""
    code: builtins.str
    """商品代碼"""
    direction: mizar_common_pb2.Action.ValueType
    """買賣方向"""
    quantity: builtins.int
    """數量"""
    price: builtins.float
    """平均價格"""
    last_price: builtins.float
    """目前價格"""
    pnl: builtins.float
    """損益"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        code: builtins.str = ...,
        direction: mizar_common_pb2.Action.ValueType = ...,
        quantity: builtins.int = ...,
        price: builtins.float = ...,
        last_price: builtins.float = ...,
        pnl: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "direction", b"direction", "id", b"id", "last_price", b"last_price", "pnl", b"pnl", "price", b"price", "quantity", b"quantity"]) -> None: ...

global___FuturePosition = FuturePosition

@typing.final
class FuturePositionDetail(google.protobuf.message.Message):
    """期貨持倉明細"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    LAST_PRICE_FIELD_NUMBER: builtins.int
    DSEQ_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    PNL_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    FEE_FIELD_NUMBER: builtins.int
    ENTRY_QUANTITY_FIELD_NUMBER: builtins.int
    date: builtins.str
    """交易日期"""
    code: builtins.str
    """商品代碼"""
    quantity: builtins.int
    """數量"""
    price: builtins.float
    """價格"""
    last_price: builtins.float
    """目前股價"""
    dseq: builtins.str
    """委託書號"""
    direction: mizar_common_pb2.Action.ValueType
    """買賣方向"""
    pnl: builtins.float
    """損益"""
    currency: builtins.str
    """幣別"""
    fee: builtins.float
    """交易手續費"""
    entry_quantity: builtins.int
    """新倉數量"""
    def __init__(
        self,
        *,
        date: builtins.str = ...,
        code: builtins.str = ...,
        quantity: builtins.int = ...,
        price: builtins.float = ...,
        last_price: builtins.float = ...,
        dseq: builtins.str = ...,
        direction: mizar_common_pb2.Action.ValueType = ...,
        pnl: builtins.float = ...,
        currency: builtins.str = ...,
        fee: builtins.float = ...,
        entry_quantity: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "currency", b"currency", "date", b"date", "direction", b"direction", "dseq", b"dseq", "entry_quantity", b"entry_quantity", "fee", b"fee", "last_price", b"last_price", "pnl", b"pnl", "price", b"price", "quantity", b"quantity"]) -> None: ...

global___FuturePositionDetail = FuturePositionDetail

@typing.final
class GetMarginRequest(google.protobuf.message.Message):
    """=============================================================================
    MQ 使用 MESSAGE 定義區
    =============================================================================

    取得保證金請求
    無參數，查詢當前帳戶保證金資訊
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetMarginRequest = GetMarginRequest

@typing.final
class GetMarginResponse(google.protobuf.message.Message):
    """取得保證金回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MARGIN_INFO_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def margin_info(self) -> global___MarginInfo:
        """保證金資訊"""

    def __init__(
        self,
        *,
        margin_info: global___MarginInfo | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["margin_info", b"margin_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "margin_info", b"margin_info"]) -> None: ...

global___GetMarginResponse = GetMarginResponse

@typing.final
class GetFuturePositionListRequest(google.protobuf.message.Message):
    """取得期貨持倉列表請求
    無參數，查詢當前帳戶所有期貨持倉
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetFuturePositionListRequest = GetFuturePositionListRequest

@typing.final
class GetFuturePositionListResponse(google.protobuf.message.Message):
    """期貨持倉列表回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUTURE_POSITIONS_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def future_positions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FuturePosition]:
        """期貨持倉列表"""

    def __init__(
        self,
        *,
        future_positions: collections.abc.Iterable[global___FuturePosition] | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "future_positions", b"future_positions"]) -> None: ...

global___GetFuturePositionListResponse = GetFuturePositionListResponse

@typing.final
class GetFuturePositionDetailRequest(google.protobuf.message.Message):
    """取得期貨持倉明細請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DETAIL_ID_FIELD_NUMBER: builtins.int
    detail_id: builtins.int
    """明細代碼（從持倉列表取得）"""
    def __init__(
        self,
        *,
        detail_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["detail_id", b"detail_id"]) -> None: ...

global___GetFuturePositionDetailRequest = GetFuturePositionDetailRequest

@typing.final
class GetFuturePositionDetailResponse(google.protobuf.message.Message):
    """期貨持倉明細回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUTURE_DETAILS_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def future_details(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FuturePositionDetail]:
        """期貨持倉明細"""

    def __init__(
        self,
        *,
        future_details: collections.abc.Iterable[global___FuturePositionDetail] | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "future_details", b"future_details"]) -> None: ...

global___GetFuturePositionDetailResponse = GetFuturePositionDetailResponse
