# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mizar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mizar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mizar_info_pb2 as mizar__info__pb2
import mizar_quote_pb2 as mizar__quote__pb2
import mizar_portfolio_pb2 as mizar__portfolio__pb2
import mizar_trade_pb2 as mizar__trade__pb2
import mizar_stream_pb2 as mizar__stream__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmizar.proto\x12\x05mizar\x1a\x10mizar_info.proto\x1a\x11mizar_quote.proto\x1a\x15mizar_portfolio.proto\x1a\x11mizar_trade.proto\x1a\x12mizar_stream.protoB*Z(github.com/mizar/mizar-proto/proto/mizarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mizar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/mizar/mizar-proto/proto/mizar'
# @@protoc_insertion_point(module_scope)
