"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import mizar_common_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FuturePlaceOrderRequest(google.protobuf.message.Message):
    """=============================================================================
    MQ 使用 MESSAGE 定義區
    =============================================================================

    期貨下單請求
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    PRICE_TYPE_FIELD_NUMBER: builtins.int
    ORDER_TYPE_FIELD_NUMBER: builtins.int
    OC_TYPE_FIELD_NUMBER: builtins.int
    code: builtins.str
    """商品代碼"""
    symbol: builtins.str
    """商品符號"""
    price: builtins.float
    """價格"""
    quantity: builtins.int
    """委託數量"""
    action: mizar_common_pb2.Action.ValueType
    """買賣方向"""
    price_type: mizar_common_pb2.PriceType.ValueType
    """價格類型"""
    order_type: mizar_common_pb2.OrderType.ValueType
    """委託類別"""
    oc_type: mizar_common_pb2.OcType.ValueType
    """委託性質"""
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
        action: mizar_common_pb2.Action.ValueType = ...,
        price_type: mizar_common_pb2.PriceType.ValueType = ...,
        order_type: mizar_common_pb2.OrderType.ValueType = ...,
        oc_type: mizar_common_pb2.OcType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action", b"action", "code", b"code", "oc_type", b"oc_type", "order_type", b"order_type", "price", b"price", "price_type", b"price_type", "quantity", b"quantity", "symbol", b"symbol"]) -> None: ...

global___FuturePlaceOrderRequest = FuturePlaceOrderRequest

@typing.final
class FuturePlaceOrderResponse(google.protobuf.message.Message):
    """期貨下單回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def trade(self) -> mizar_common_pb2.Trade:
        """完整的委託交易資訊"""

    def __init__(
        self,
        *,
        trade: mizar_common_pb2.Trade | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trade", b"trade"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "trade", b"trade"]) -> None: ...

global___FuturePlaceOrderResponse = FuturePlaceOrderResponse

@typing.final
class FutureUpdateOrderRequest(google.protobuf.message.Message):
    """期貨改單請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    PRICE_TYPE_FIELD_NUMBER: builtins.int
    ORDER_TYPE_FIELD_NUMBER: builtins.int
    OC_TYPE_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    """委託單號"""
    price: builtins.float
    """新價格"""
    quantity: builtins.int
    """新委託數量"""
    price_type: mizar_common_pb2.PriceType.ValueType
    """新價格類型"""
    order_type: mizar_common_pb2.OrderType.ValueType
    """新委託類別"""
    oc_type: mizar_common_pb2.OcType.ValueType
    """新委託性質"""
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
        price_type: mizar_common_pb2.PriceType.ValueType = ...,
        order_type: mizar_common_pb2.OrderType.ValueType = ...,
        oc_type: mizar_common_pb2.OcType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["oc_type", b"oc_type", "order_id", b"order_id", "order_type", b"order_type", "price", b"price", "price_type", b"price_type", "quantity", b"quantity"]) -> None: ...

global___FutureUpdateOrderRequest = FutureUpdateOrderRequest

@typing.final
class FutureUpdateOrderResponse(google.protobuf.message.Message):
    """期貨改單回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def trade(self) -> mizar_common_pb2.Trade:
        """更新後的委託交易資訊"""

    def __init__(
        self,
        *,
        trade: mizar_common_pb2.Trade | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trade", b"trade"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "trade", b"trade"]) -> None: ...

global___FutureUpdateOrderResponse = FutureUpdateOrderResponse

@typing.final
class FutureCancelOrderRequest(google.protobuf.message.Message):
    """期貨刪單請求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    """委託單號"""
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["order_id", b"order_id"]) -> None: ...

global___FutureCancelOrderRequest = FutureCancelOrderRequest

@typing.final
class FutureCancelOrderResponse(google.protobuf.message.Message):
    """期貨刪單回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def trade(self) -> mizar_common_pb2.Trade:
        """刪單後的委託交易資訊"""

    def __init__(
        self,
        *,
        trade: mizar_common_pb2.Trade | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trade", b"trade"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "trade", b"trade"]) -> None: ...

global___FutureCancelOrderResponse = FutureCancelOrderResponse

@typing.final
class GetOrderStatusRequest(google.protobuf.message.Message):
    """取得委託狀態請求
    無參數，查詢所有委託狀態
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetOrderStatusRequest = GetOrderStatusRequest

@typing.final
class GetOrderStatusResponse(google.protobuf.message.Message):
    """取得委託狀態回應"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADES_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: mizar_common_pb2.ErrorCode.ValueType
    """錯誤代碼"""
    error_message: builtins.str
    """錯誤訊息"""
    @property
    def trades(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[mizar_common_pb2.Trade]:
        """委託交易列表"""

    def __init__(
        self,
        *,
        trades: collections.abc.Iterable[mizar_common_pb2.Trade] | None = ...,
        error_code: mizar_common_pb2.ErrorCode.ValueType = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "trades", b"trades"]) -> None: ...

global___GetOrderStatusResponse = GetOrderStatusResponse
