"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERROR_CODE_SUCCESS: _ErrorCode.ValueType  # 0
    """成功"""
    ERROR_CODE_API_NOT_READY: _ErrorCode.ValueType  # 1
    """API 未就緒（連線失敗）"""
    ERROR_CODE_RATE_LIMIT: _ErrorCode.ValueType  # 2
    """流量限制"""
    ERROR_CODE_INTERNAL_ERROR: _ErrorCode.ValueType  # 99
    """內部錯誤（未預期的錯誤）"""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper):
    """=============================================================================
    共用 ENUM 定義區
    =============================================================================

    錯誤代碼
    """

ERROR_CODE_SUCCESS: ErrorCode.ValueType  # 0
"""成功"""
ERROR_CODE_API_NOT_READY: ErrorCode.ValueType  # 1
"""API 未就緒（連線失敗）"""
ERROR_CODE_RATE_LIMIT: ErrorCode.ValueType  # 2
"""流量限制"""
ERROR_CODE_INTERNAL_ERROR: ErrorCode.ValueType  # 99
"""內部錯誤（未預期的錯誤）"""
global___ErrorCode = ErrorCode

class _Action:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Action.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACTION_UNSPECIFIED: _Action.ValueType  # 0
    """未定義"""
    ACTION_BUY: _Action.ValueType  # 1
    """買"""
    ACTION_SELL: _Action.ValueType  # 2
    """賣"""

class Action(_Action, metaclass=_ActionEnumTypeWrapper):
    """買賣方向"""

ACTION_UNSPECIFIED: Action.ValueType  # 0
"""未定義"""
ACTION_BUY: Action.ValueType  # 1
"""買"""
ACTION_SELL: Action.ValueType  # 2
"""賣"""
global___Action = Action

class _PriceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PriceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PriceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRICE_TYPE_UNSPECIFIED: _PriceType.ValueType  # 0
    """未定義"""
    PRICE_TYPE_LMT: _PriceType.ValueType  # 1
    """限價"""
    PRICE_TYPE_MKT: _PriceType.ValueType  # 2
    """市價"""
    PRICE_TYPE_MKP: _PriceType.ValueType  # 3
    """範圍市價"""

class PriceType(_PriceType, metaclass=_PriceTypeEnumTypeWrapper):
    """價格類型"""

PRICE_TYPE_UNSPECIFIED: PriceType.ValueType  # 0
"""未定義"""
PRICE_TYPE_LMT: PriceType.ValueType  # 1
"""限價"""
PRICE_TYPE_MKT: PriceType.ValueType  # 2
"""市價"""
PRICE_TYPE_MKP: PriceType.ValueType  # 3
"""範圍市價"""
global___PriceType = PriceType

class _OrderType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OrderType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ORDER_TYPE_UNSPECIFIED: _OrderType.ValueType  # 0
    """未定義"""
    ORDER_TYPE_ROD: _OrderType.ValueType  # 1
    """ROD（當日有效）"""
    ORDER_TYPE_IOC: _OrderType.ValueType  # 2
    """IOC（立即成交否則取消）"""
    ORDER_TYPE_FOK: _OrderType.ValueType  # 3
    """FOK（全部成交否則取消）"""

class OrderType(_OrderType, metaclass=_OrderTypeEnumTypeWrapper):
    """委託類別"""

ORDER_TYPE_UNSPECIFIED: OrderType.ValueType  # 0
"""未定義"""
ORDER_TYPE_ROD: OrderType.ValueType  # 1
"""ROD（當日有效）"""
ORDER_TYPE_IOC: OrderType.ValueType  # 2
"""IOC（立即成交否則取消）"""
ORDER_TYPE_FOK: OrderType.ValueType  # 3
"""FOK（全部成交否則取消）"""
global___OrderType = OrderType

class _OcType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OcTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OcType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OC_TYPE_UNSPECIFIED: _OcType.ValueType  # 0
    """未定義"""
    OC_TYPE_AUTO: _OcType.ValueType  # 1
    """自動"""
    OC_TYPE_NEW: _OcType.ValueType  # 2
    """新倉"""
    OC_TYPE_COVER: _OcType.ValueType  # 3
    """平倉"""
    OC_TYPE_DAY_TRADE: _OcType.ValueType  # 4
    """當沖"""

class OcType(_OcType, metaclass=_OcTypeEnumTypeWrapper):
    """委託性質"""

OC_TYPE_UNSPECIFIED: OcType.ValueType  # 0
"""未定義"""
OC_TYPE_AUTO: OcType.ValueType  # 1
"""自動"""
OC_TYPE_NEW: OcType.ValueType  # 2
"""新倉"""
OC_TYPE_COVER: OcType.ValueType  # 3
"""平倉"""
OC_TYPE_DAY_TRADE: OcType.ValueType  # 4
"""當沖"""
global___OcType = OcType

class _OrderStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OrderStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ORDER_STATUS_UNSPECIFIED: _OrderStatus.ValueType  # 0
    """未定義"""
    ORDER_STATUS_CANCELLED: _OrderStatus.ValueType  # 1
    """已刪除"""
    ORDER_STATUS_FILLED: _OrderStatus.ValueType  # 2
    """完全成交"""
    ORDER_STATUS_PART_FILLED: _OrderStatus.ValueType  # 3
    """部分成交"""
    ORDER_STATUS_FAILED: _OrderStatus.ValueType  # 4
    """失敗"""
    ORDER_STATUS_PENDING_SUBMIT: _OrderStatus.ValueType  # 5
    """傳送中"""
    ORDER_STATUS_PRE_SUBMITTED: _OrderStatus.ValueType  # 6
    """預約單"""
    ORDER_STATUS_SUBMITTED: _OrderStatus.ValueType  # 7
    """傳送成功"""

class OrderStatus(_OrderStatus, metaclass=_OrderStatusEnumTypeWrapper):
    """委託狀態"""

ORDER_STATUS_UNSPECIFIED: OrderStatus.ValueType  # 0
"""未定義"""
ORDER_STATUS_CANCELLED: OrderStatus.ValueType  # 1
"""已刪除"""
ORDER_STATUS_FILLED: OrderStatus.ValueType  # 2
"""完全成交"""
ORDER_STATUS_PART_FILLED: OrderStatus.ValueType  # 3
"""部分成交"""
ORDER_STATUS_FAILED: OrderStatus.ValueType  # 4
"""失敗"""
ORDER_STATUS_PENDING_SUBMIT: OrderStatus.ValueType  # 5
"""傳送中"""
ORDER_STATUS_PRE_SUBMITTED: OrderStatus.ValueType  # 6
"""預約單"""
ORDER_STATUS_SUBMITTED: OrderStatus.ValueType  # 7
"""傳送成功"""
global___OrderStatus = OrderStatus

class _TickType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TickTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TickType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TICK_TYPE_UNKNOWN: _TickType.ValueType  # 0
    """無法判定"""
    TICK_TYPE_OUTSIDE: _TickType.ValueType  # 1
    """外盤"""
    TICK_TYPE_INSIDE: _TickType.ValueType  # 2
    """內盤"""

class TickType(_TickType, metaclass=_TickTypeEnumTypeWrapper):
    """內外盤別"""

TICK_TYPE_UNKNOWN: TickType.ValueType  # 0
"""無法判定"""
TICK_TYPE_OUTSIDE: TickType.ValueType  # 1
"""外盤"""
TICK_TYPE_INSIDE: TickType.ValueType  # 2
"""內盤"""
global___TickType = TickType

class _ChangeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChangeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChangeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHANGE_TYPE_UNKNOWN: _ChangeType.ValueType  # 0
    """未知"""
    CHANGE_TYPE_LIMIT_UP: _ChangeType.ValueType  # 1
    """漲停"""
    CHANGE_TYPE_UP: _ChangeType.ValueType  # 2
    """漲"""
    CHANGE_TYPE_FLAT: _ChangeType.ValueType  # 3
    """平盤"""
    CHANGE_TYPE_DOWN: _ChangeType.ValueType  # 4
    """跌"""
    CHANGE_TYPE_LIMIT_DOWN: _ChangeType.ValueType  # 5
    """跌停"""

class ChangeType(_ChangeType, metaclass=_ChangeTypeEnumTypeWrapper):
    """漲跌註記"""

CHANGE_TYPE_UNKNOWN: ChangeType.ValueType  # 0
"""未知"""
CHANGE_TYPE_LIMIT_UP: ChangeType.ValueType  # 1
"""漲停"""
CHANGE_TYPE_UP: ChangeType.ValueType  # 2
"""漲"""
CHANGE_TYPE_FLAT: ChangeType.ValueType  # 3
"""平盤"""
CHANGE_TYPE_DOWN: ChangeType.ValueType  # 4
"""跌"""
CHANGE_TYPE_LIMIT_DOWN: ChangeType.ValueType  # 5
"""跌停"""
global___ChangeType = ChangeType

class _SimTradeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SimTradeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SimTradeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SIM_TRADE_TYPE_NORMAL: _SimTradeType.ValueType  # 0
    """正常交易"""
    SIM_TRADE_TYPE_SIMULATION: _SimTradeType.ValueType  # 1
    """試撮"""

class SimTradeType(_SimTradeType, metaclass=_SimTradeTypeEnumTypeWrapper):
    """試撮狀態"""

SIM_TRADE_TYPE_NORMAL: SimTradeType.ValueType  # 0
"""正常交易"""
SIM_TRADE_TYPE_SIMULATION: SimTradeType.ValueType  # 1
"""試撮"""
global___SimTradeType = SimTradeType

@typing.final
class Deal(google.protobuf.message.Message):
    """=============================================================================
    共用 MESSAGE 定義區
    =============================================================================

    成交資訊
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQ_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    TS_FIELD_NUMBER: builtins.int
    seq: builtins.str
    """成交序號"""
    price: builtins.float
    """成交價"""
    quantity: builtins.int
    """成交數量"""
    ts: builtins.int
    """成交時間戳（納秒）"""
    def __init__(
        self,
        *,
        seq: builtins.str = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
        ts: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["price", b"price", "quantity", b"quantity", "seq", b"seq", "ts", b"ts"]) -> None: ...

global___Deal = Deal

@typing.final
class OrderStatusInfo(google.protobuf.message.Message):
    """委託狀態資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STATUS_CODE_FIELD_NUMBER: builtins.int
    ORDER_DATETIME_FIELD_NUMBER: builtins.int
    ORDER_QUANTITY_FIELD_NUMBER: builtins.int
    MODIFIED_PRICE_FIELD_NUMBER: builtins.int
    CANCEL_QUANTITY_FIELD_NUMBER: builtins.int
    DEALS_FIELD_NUMBER: builtins.int
    id: builtins.str
    """關聯Order物件編碼"""
    status: global___OrderStatus.ValueType
    """委託狀態"""
    status_code: builtins.str
    """狀態碼"""
    order_datetime: builtins.int
    """委託時間（納秒時間戳）"""
    order_quantity: builtins.int
    """委託數量"""
    modified_price: builtins.float
    """改價金額"""
    cancel_quantity: builtins.int
    """取消委託數量"""
    @property
    def deals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Deal]:
        """成交資訊"""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        status: global___OrderStatus.ValueType = ...,
        status_code: builtins.str = ...,
        order_datetime: builtins.int = ...,
        order_quantity: builtins.int = ...,
        modified_price: builtins.float = ...,
        cancel_quantity: builtins.int = ...,
        deals: collections.abc.Iterable[global___Deal] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cancel_quantity", b"cancel_quantity", "deals", b"deals", "id", b"id", "modified_price", b"modified_price", "order_datetime", b"order_datetime", "order_quantity", b"order_quantity", "status", b"status", "status_code", b"status_code"]) -> None: ...

global___OrderStatusInfo = OrderStatusInfo

@typing.final
class Order(google.protobuf.message.Message):
    """委託資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTION_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    SEQNO_FIELD_NUMBER: builtins.int
    ORDNO_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_FIELD_NUMBER: builtins.int
    PRICE_TYPE_FIELD_NUMBER: builtins.int
    ORDER_TYPE_FIELD_NUMBER: builtins.int
    DAYTRADE_SHORT_FIELD_NUMBER: builtins.int
    OC_TYPE_FIELD_NUMBER: builtins.int
    action: global___Action.ValueType
    """買賣方向"""
    price: builtins.float
    """委託價格"""
    quantity: builtins.int
    """委託數量"""
    id: builtins.str
    """委託編號"""
    seqno: builtins.str
    """平台單號"""
    ordno: builtins.str
    """委託序號"""
    account: builtins.str
    """帳號"""
    custom_field: builtins.str
    """自訂欄位"""
    price_type: global___PriceType.ValueType
    """價格類型"""
    order_type: global___OrderType.ValueType
    """委託類別"""
    daytrade_short: builtins.bool
    """當沖賣空（證券用）"""
    oc_type: global___OcType.ValueType
    """委託性質（期貨用）"""
    def __init__(
        self,
        *,
        action: global___Action.ValueType = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
        id: builtins.str = ...,
        seqno: builtins.str = ...,
        ordno: builtins.str = ...,
        account: builtins.str = ...,
        custom_field: builtins.str = ...,
        price_type: global___PriceType.ValueType = ...,
        order_type: global___OrderType.ValueType = ...,
        daytrade_short: builtins.bool = ...,
        oc_type: global___OcType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "action", b"action", "custom_field", b"custom_field", "daytrade_short", b"daytrade_short", "id", b"id", "oc_type", b"oc_type", "order_type", b"order_type", "ordno", b"ordno", "price", b"price", "price_type", b"price_type", "quantity", b"quantity", "seqno", b"seqno"]) -> None: ...

global___Order = Order

@typing.final
class Contract(google.protobuf.message.Message):
    """商品資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    LIMIT_UP_FIELD_NUMBER: builtins.int
    LIMIT_DOWN_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    DELIVERY_MONTH_FIELD_NUMBER: builtins.int
    DELIVERY_DATE_FIELD_NUMBER: builtins.int
    UNDERLYING_KIND_FIELD_NUMBER: builtins.int
    code: builtins.str
    """商品代碼"""
    symbol: builtins.str
    """商品符號"""
    name: builtins.str
    """商品名稱"""
    category: builtins.str
    """商品類別"""
    unit: builtins.int
    """交易單位"""
    limit_up: builtins.float
    """漲停價"""
    limit_down: builtins.float
    """跌停價"""
    reference: builtins.float
    """參考價"""
    update_date: builtins.str
    """更新日期"""
    delivery_month: builtins.str
    """到期月份（期貨用）"""
    delivery_date: builtins.str
    """到期日期（期貨用）"""
    underlying_kind: builtins.str
    """標的物種類（期貨用）"""
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
        category: builtins.str = ...,
        unit: builtins.int = ...,
        limit_up: builtins.float = ...,
        limit_down: builtins.float = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
        delivery_month: builtins.str = ...,
        delivery_date: builtins.str = ...,
        underlying_kind: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "delivery_date", b"delivery_date", "delivery_month", b"delivery_month", "limit_down", b"limit_down", "limit_up", b"limit_up", "name", b"name", "reference", b"reference", "symbol", b"symbol", "underlying_kind", b"underlying_kind", "unit", b"unit", "update_date", b"update_date"]) -> None: ...

global___Contract = Contract

@typing.final
class Trade(google.protobuf.message.Message):
    """委託交易資訊"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def contract(self) -> global___Contract:
        """商品資訊"""

    @property
    def order(self) -> global___Order:
        """委託資訊"""

    @property
    def status(self) -> global___OrderStatusInfo:
        """委託狀態"""

    def __init__(
        self,
        *,
        contract: global___Contract | None = ...,
        order: global___Order | None = ...,
        status: global___OrderStatusInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["contract", b"contract", "order", b"order", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["contract", b"contract", "order", b"order", "status", b"status"]) -> None: ...

global___Trade = Trade
